"""Remote store message schemas and HTTP JSON adapter."""

from mneme.remote._http import (
    HttpJsonRequester,
    HttpJsonResponse,
    MemoryStoreASGIApp,
    RemoteHttpClient,
    RemoteHttpConfig,
    RemoteStoreBackend,
    serve_asgi_app,
)
from mneme.remote._messages import (
    ERROR_SCHEMA,
    PROVE_REQUEST_SCHEMA,
    PROVE_RESPONSE_SCHEMA,
    PUT_REQUEST_SCHEMA,
    PUT_RESPONSE_SCHEMA,
    QUERY_REQUEST_SCHEMA,
    QUERY_RESPONSE_SCHEMA,
    ROOT_REQUEST_SCHEMA,
    ROOT_RESPONSE_SCHEMA,
    STATS_REQUEST_SCHEMA,
    STATS_RESPONSE_SCHEMA,
    ErrorMessage,
    MemoryItemEnvelope,
    ProveRequest,
    ProveResponse,
    PutRequest,
    PutResponse,
    QueryRequest,
    QueryResponse,
    RemoteArray,
    RootRequest,
    RootResponse,
    StatsRequest,
    StatsResponse,
)
from mneme.remote._validation import raise_for_remote_error, validate_query_response

__all__ = [
    "ERROR_SCHEMA",
    "HttpJsonRequester",
    "HttpJsonResponse",
    "MemoryStoreASGIApp",
    "PROVE_REQUEST_SCHEMA",
    "PROVE_RESPONSE_SCHEMA",
    "PUT_REQUEST_SCHEMA",
    "PUT_RESPONSE_SCHEMA",
    "QUERY_REQUEST_SCHEMA",
    "QUERY_RESPONSE_SCHEMA",
    "ROOT_REQUEST_SCHEMA",
    "ROOT_RESPONSE_SCHEMA",
    "STATS_REQUEST_SCHEMA",
    "STATS_RESPONSE_SCHEMA",
    "ErrorMessage",
    "MemoryItemEnvelope",
    "ProveRequest",
    "ProveResponse",
    "PutRequest",
    "PutResponse",
    "QueryRequest",
    "QueryResponse",
    "RemoteArray",
    "RemoteHttpClient",
    "RemoteHttpConfig",
    "RemoteStoreBackend",
    "RootRequest",
    "RootResponse",
    "StatsRequest",
    "StatsResponse",
    "raise_for_remote_error",
    "serve_asgi_app",
    "validate_query_response",
]
